// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBPLbh78A8T81lEetklx3Sh5-rzbLFXuA',
    appId: '1:773540417152:web:414caae5962467b5d86065',
    messagingSenderId: '773540417152',
    projectId: 'userauth-35876',
    authDomain: 'userauth-35876.firebaseapp.com',
    storageBucket: 'userauth-35876.appspot.com',
    measurementId: 'G-LQC1R0QQLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl80l-_HBmzCOGDwJpVqyr1g1S7mT61YI',
    appId: '1:773540417152:android:b714d5303b4500a7d86065',
    messagingSenderId: '773540417152',
    projectId: 'userauth-35876',
    storageBucket: 'userauth-35876.appspot.com',
  );
}
